# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{games_radar}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2011-03-22}
  s.description = %q{GamesRadar is an API wrapper for the games website http://gamesradar.com}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "README.rdoc",
    "lib/games-radar.rb",
    "lib/games_radar.rb",
    "lib/games_radar/config.rb",
    "lib/games_radar/errors.rb",
    "lib/games_radar/game.rb",
    "lib/games_radar/genre.rb",
    "lib/games_radar/platform.rb",
    "lib/games_radar/request.rb",
    "lib/games_radar/result.rb",
    "lib/games_radar/screenshot.rb",
    "lib/games_radar/version.rb",
    "test/config_test.rb",
    "test/game_test.rb",
    "test/games_radar_test.rb",
    "test/genre_test.rb",
    "test/platform_test.rb",
    "test/request_test.rb",
    "test/resources/game.xml",
    "test/resources/game_not_found.xml",
    "test/resources/games.xml",
    "test/resources/invalid_api_key.xml",
    "test/resources/no_games.xml",
    "test/resources/platforms.xml",
    "test/resources/screenshots.xml",
    "test/result_test.rb",
    "test/screenshot_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/fnando/games_radar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{GamesRadar is an API wrapper for the games website http://gamesradar.com}
  s.test_files = [
    "test/config_test.rb",
    "test/game_test.rb",
    "test/games_radar_test.rb",
    "test/genre_test.rb",
    "test/platform_test.rb",
    "test/request_test.rb",
    "test/result_test.rb",
    "test/screenshot_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<games_radar>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<hanna>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<hanna>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<games_radar>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<hanna>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<hanna>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<games_radar>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<hanna>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<hanna>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

